config/routes.rb
Rails.application.routes.draw do
	resources :articles do
		collection do
			get "map"
		end
		member do
		  post "save_content", to: "articles#save_content"
		end
	  end


	get 'admin/integrations', to: 'page#integrations'
	get 'admin/team', to: 'page#team'
	get 'admin/billing', to: 'page#billing'
	get 'admin/notifications', to: 'page#notifications'
	get 'admin/settings', to: 'page#settings'
	get 'admin/activity', to: 'page#activity'
	get 'admin/profile', to: 'page#profile'
	get 'admin/people', to: 'page#people'
	get 'admin/calendar', to: 'page#calendar'
	get 'admin/assignments', to: 'page#assignments'
	get 'admin/message', to: 'page#message'
	get 'admin/messages', to: 'page#messages'
	get 'admin/project', to: 'page#project'
	get 'admin/projects', to: 'page#projects'
	get 'admin/dashboard', to: 'page#dashboard'
	get 'about', to: 'page#about'
  if Rails.env.development? || Rails.env.test?
    mount Railsui::Engine, at: "/railsui"
  end

  # Inherits from Railsui::PageController#index
  # To overide, add your own page#index view or change to a new root
  # Visit the start page for Rails UI any time at /railsui/start
  root "page#index"

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
include PgSearch::Model

class Article < ApplicationRecord
    has_one_attached :image
    
    has_rich_text :contenu

    pg_search_scope :search_by_title,
    against: [:title],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/user.rb
class User < ApplicationRecord
  has_person_name
  has_one_attached :avatar
  has_one_attached :photo

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper Railsui::ThemeHelper

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:avatar, :name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:avatar, :name])
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: %i[ show edit update destroy ]

  # GET /articles or /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy!

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end


  def save_content
    contenu = params[:contenu]
    @article = Article.find(params[:id])
    if @article.update(contenu: contenu)
      render json: { success: true , contenu: @article.contenu}
    else  
      render json: { success: false, errors: @article.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def map
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :topic, :image, :contenu)
    end

end

app/controllers/page_controller.rb
class PageController < ApplicationController

	def integrations
		render layout: 'admin'
	end

	def team
		render layout: 'admin'
	end

	def billing
		render layout: 'admin'
	end

	def notifications
		render layout: 'admin'
	end

	def settings
		render layout: 'admin'
	end

	def activity
		render layout: 'admin'
	end

	def profile
		render layout: 'admin'
	end

	def people
		render layout: 'admin'
	end

	def calendar
		render layout: 'admin'
	end

	def assignments
		render layout: 'admin'
	end

	def message
		render layout: 'admin'
	end

	def messages
		render layout: 'admin'
	end

	def project
		render layout: 'admin'
	end

	def projects
		render layout: 'admin'
	end

	def dashboard
		render layout: 'admin'
	end

	def about
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    # ...
  
    # POST /users or /users.json
    def create
      @user = User.new(user_params)
  
      respond_to do |format|
        if @user.save
          # Tell the UserMailer to send a welcome email after save
          UserMailer.with(user: @user).welcome_email.deliver_later
  
          format.html { redirect_to(@user, notice: 'User was successfully created.') }
          format.json { render json: @user, status: :created, location: @user }
        else
          format.html { render action: 'new' }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # ...
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/articles/_article.html.erb
<% content_for :head do %>

  <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
  <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">
  
<%end%>


<article>
  <div class="flex items-start space-x-6">
  <%if article.try(:image).present?%>
    <%= image_tag(article.image, class: "w-40 h-auto rounded-xl object-cover group-hover:scale-110 transition ease-in-out duration-300", alt: article.title) %>
  <% end %>


    <div class="flex-1">
      <header>
        <h1 class="font-semibold text-base dark:text-zinc-100"><%= article.title %></h1>
      </header>

      <div class="prose prose-zinc dark:prose-invert font-heading font-light my-3 max-w-md">
        <p><%= article.topic %></p>
      </div>
    </div>
  </div>
<div class="mt-10">
  <%= article.contenu%>
</div>




</article>

app/views/articles/_article_header.html.erb
<article class="border-2 border-sky-500 rounded-xl">
  <div class="flex items-start space-x-6 m-4">
    <%if article.try(:image).present?%>
      <%= image_tag(article.image, class: "w-40 h-auto rounded-xl object-cover group-hover:scale-110 transition ease-in-out duration-300", alt: article.title) %>
    <% end %>


    <div class="flex-1">
      <header>
        <h1 class="font-semibold text-base dark:text-zinc-100"><%= article.title %></h1>
      </header>

      <div class="prose prose-zinc dark:prose-invert font-heading font-light my-3 max-w-md">
        <p><%= article.topic %></p>
      </div>
      <footer>
      <%= link_to "Read now", article_path(article), class: "btn btn-white md:mt-1 mt-2 inline-flex items-center" %>
      </footer>
    </div>
  </div>
</article>

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <%= render "shared/error_messages", resource: form.object %>

  <div class="form-group mr-20">
    <%= form.label :title, class: "form-label" %>
    <%= form.text_field :title, class: "form-input" %>
  </div>

  <div class="form-group mr-20">
    <%= form.label :topic, class: "form-label" %>
    <%= form.text_field :topic, class: "form-input" %>
  </div>

  <div class="mt-10">
    <%= form.label :image, class: "form-label" %>
    <%= form.file_field :image %>
  </div>

  <div class="mt-10">
    <%= form.label :contenu, class: "form-label" %>
    <%= form.rich_text_area :contenu %>
  </div>

  <div class="flex items-center justify-between flex-wrap mt-10">
    <div class="sm:flex-1 sm:mb-0 mb-6">
      <%= form.submit class: "btn btn-primary" %>
    </div>

    <% if form.object.new_record? %>
      <%= link_to "Cancel", articles_path, class: "btn btn-white" %>
    <% else %>
      <%= link_to "Cancel", article_path(@article), class: "btn btn-white" %>
    <% end %>
  </div>
<% end %>

app/views/articles/_search_bar.html.erb
<form class="max-w-md mx-auto">   
    <label for="default-search" class="mb-2 text-sm font-medium text-gray-900 sr-only dark:text-white">Search</label>
    <div class="relative">
        <div class="absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none">
            <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"/>
            </svg>
        </div>
        <input type="search" id="default-search" class="block w-full p-4 ps-10 text-sm text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Search Mockups, Logos..." required />
        <button type="submit" class="text-white absolute end-2.5 bottom-2.5 bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Search</button>
    </div>
</form>

app/views/articles/_secondary_nav.html.erb
<div
  id="dropdowns-navigation"
  class="lg:flex-1 lg:block hidden lg:static absolute top-12 left-0 w-full bg-white dark:bg-slate-900 lg:bg-transparent transform origin-top px-4 pb-4 lg:p-0 rounded-b lg:shadow-none shadow-xl z-40 text-base mt-4"
  data-nav-target="nav"
  data-transition-enter-active="transition ease-out duration-200"
  data-transition-enter-from="opacity-0 scale-95"
  data-transition-enter-to="opacity-100 scale-100"
  data-transition-leave-from="opacity-100 scale-100"
  data-transition-leave-active="transition ease-in duration-200"
  data-transition-leave-to="opacity-0 scale-95"
>
  <nav role="secondary navigation">
    <ul class="flex justify-center space-x-12">
      <li class=>
        <%= nav_link_to "Search Bar", articles_path, class:"nav-link"%>
      </li>
      <li >
        <%= nav_link_to "Search Map", "/articles/map", class: "nav-link" %>
      </li>
    </ul>
  </nav>
</div>

app/views/articles/edit.html.erb
<div class="max-w-3xl mx-auto px-4 my-16">
  <div class="mb-4 pb-6 border-b dark:border-zinc-700">
    <nav aria-label="breadcrumb" class="my-6 font-heading flex text-zinc-500 dark:text-zinc-200 text-sm">
      <ol class="flex flex-wrap items-center space-x-3 list-none m-0 p-0">
        <li>
          <%= link_to "Articles", articles_path, class: "hover:underline text-primary-600 dark:text-primary-500" %>
        </li>
        <li class="flex space-x-3">
          <div class="flex items-center">
            <span class="text-zinc-300 dark:text-zinc-500">/</span>
          </div>
          <span class="text-zinc-600 dark:text-zinc-100" aria-current="page">Edit</span>
        </li>
      </ol>
    </nav>
    <div class="flex items-center justify-between">
      <h1 class="text-4xl font-semibold font-heading text-zinc-900 dark:text-zinc-100 tracking-tight">Edit Article</h1>
      <%= button_to "Delete", @article, method: :delete, class: "btn btn-white", form: { data: { turbo_confirm: "Are you sure?" } } %>
    </div>
  </div>

  <div>
    <%= render "form", article: @article %>
  </div>
</div>

app/views/articles/index.html.erb
<%=render "secondary_nav"%>





<div class="container mx-auto px-4 py-4 pb-24 pt-1 mt-8">

<%=render "search_bar"%>

  <div class="grid grid-cols-1 lg:grid-cols-3 gap-16 mt-10">

    <% @articles.each do |article| %>
      <%=render partial: 'article_header', locals: {article: article}%>
    <%end%>


  </div>
  <%if signed_in? && current_user.admin?%>
    <%= link_to "create new article", new_article_path, class: "btn btn-primary md:mt-10 mt-2 mx-2" %>
  <%end%>
</div>

app/views/articles/map.html.erb
<% content_for :head do %>
 <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"
     integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY="
     crossorigin=""/>


 <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"
     integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo="
     crossorigin=""></script>
<%end%>

<%=render "secondary_nav"%>

<div class="flex items-center justify-center h-screen">
    <div id="map" class="w-full h-full max-w-screen-lg max-h-screen-lg">

    <script>
    var map = L.map('map').setView([51.505, -0.09], 13);

    L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
        maxZoom: 19,
        attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
    }).addTo(map);
    </script>

    </div>
</div>  

app/views/articles/new.html.erb
<div class="max-w-3xl mx-auto px-4 my-16">
  <div class="mb-4 pb-6 border-b dark:border-zinc-700">
    <nav aria-label="breadcrumb" class="my-6 font-heading flex text-zinc-500 dark:text-zinc-200 text-sm">
      <ol class="flex flex-wrap items-center space-x-3 list-none m-0 p-0">
        <li>
          <%= link_to "Articles", articles_path, class: "hover:underline text-primary-600 dark:text-primary-500" %>
        </li>
        <li class="flex space-x-3">
          <div class="flex items-center">
            <span class="text-zinc-300 dark:text-zinc-500">/</span>
          </div>
          <span class="text-zinc-600 dark:text-zinc-100" aria-current="page">New</span>
        </li>
      </ol>
    </nav>
    <h1 class="text-4xl font-semibold font-heading text-zinc-900 dark:text-zinc-100 tracking-tight">New Article</h1>
  </div>

  <div>
    <%= render "form", article: @article %>
  </div>
</div>

app/views/articles/show.html.erb
<div class="max-w-3xl mx-auto px-4 my-16">
  <div class="pb-6 border-b dark:border-zinc-700 border-zinc-200">
    <nav aria-label="breadcrumb" class="my-6 font-heading flex text-zinc-500 dark:text-zinc-200 text-sm">
      <ol class="flex flex-wrap items-center space-x-3 list-none m-0 p-0">
        <li>
          <%= link_to "Articles", articles_path, class: "hover:underline text-primary-600 dark:text-primary-500" %>
        </li>
        <li class="flex space-x-3">
          <div class="flex items-center">
            <span class="text-zinc-300 dark:text-zinc-500">/</span>
          </div>
          <span class="text-zinc-600 dark:text-zinc-100" aria-current="page">
            <%= @article.title %>
          </span>
        </li>
      </ol>
    </nav>


  <%= render partial: "article", locals:{article:@article} %>

  </div>

  <div class="flex items-center justify-between">      
    <%if signed_in? && current_user.admin?%>
    <%= link_to "Edit", edit_article_path(@article), class: "btn btn-white mt-10" %>
    <%end%>

    <%= link_to "Comment", edit_article_path(@article), class: "btn btn-white mt-10" %>

  </div>
</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
  <title>Admin | <%= Railsui.config.application_name %></title>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  <%= stylesheet_link_tag "application", "https://unpkg.com/trix@2.0.0/dist/trix.css", "data-turbo-track": "reload" %>

  <%= render "shared/fonts" %>
  <%= render "shared/meta" %>
  <%= custom_colors_css %>
  <%= yield :head %>
</head>

<body class="rui-admin antialiased h-full bg-slate-50 dark:bg-slate-900 dark:text-slate-100 text-slate-800">
  <%= render "shared/flash" %>

  <%= yield %>

  <%= railsui_launcher if Rails.env.development? %>
</body>
</html

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= "Travel with me" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= stylesheet_link_tag "application", "https://unpkg.com/trix@2.0.0/dist/trix.css", "data-turbo-track": "reload" %>

    <%= render "shared/fonts" %>
    <%= render "shared/meta" %>
    <%= custom_colors_css %>
    <%= yield :head %>
  </head>

  <body class="font-normal leading-normal text-slate-800 relative selection:bg-primary-500/40 bg-white dark:bg-slate-900 dark:text-slate-100 antialiased">
    <%= render "shared/flash" %>
    <% if content_for(:header).present? %>
      <%= yield :header %>
    <% else %>
      <%= render "shared/nav" %>
    <% end %>
    <%= yield %>
    <%= railsui_launcher if Rails.env.development? %>
  </body>
</html>

app/views/page/index.html.erb
<% content_for :header do %>
<header class="bg-cover bg-center relative bg-no-repeat" style="background-image: url(<%= asset_url("fusion.png") %>);" data-controller="nav">
  <div class="dark:bg-slate-900">
    <%= render "shared/nav_menu" %>
  </div>
</header>
<% end %>
  <div class="container mx-auto sm:py-24 pb-10 px-4 relative z-10 flex flex-wrap items-center justify-between">
    <div class="xl:w-2/5 w-full xl:text-left text-center xl:pr-16">
      <h1 class="text-5xl font-extrabold text-slate-900 dark:text-slate-100 tracking-tight">Travel with me !</h1>
      <p class="my-6 text-slate-700 dark:text-slate-400 text-lg"> I am a traveller seaking to share my experiences.<br><br>
      If you want, you can also be part of this adventure. The purpose of this website is to map and reference unknown places that should be better recognized.<br><br>
      Weather it be for the culture, the food, the arquitecture, the nature, feel free to share with me these places that you visited and will not forget.</p>
      <div class="xl:flex grid grid-cols-1 gap-4 mt-20">
        <%= link_to "message me", "#", class: "btn btn-primary btn-lg mx-10" %>
        <% if user_signed_in? %>
          <%= link_to "write an article", new_article_path, class: "btn btn-primary btn-lg" %>
        <% else %>
          <%= link_to "Log in to write an article", new_user_session_path, class: "btn btn-secondary btn-lg" %>
        <% end %>
      </div>
    </div>
   <div class="xl:w-3/5 w-full xl:my-0 mt-6 mb-10">
  <div class="flex justify-center relative">
    <%= image_tag "ipanema.jpg", alt: "Team", class: "max-w-full xl:max-w-lg 2xl:max-w-xl object-cover rounded-3xl relative z-20 shadow-2xl shadow-slate-500/20" %>
    <div
      class="w-[450px] h-[450px] bg-primary-500/10 absolute -bottom-10 left-5 rounded-full z-0 blur-2xl sm:block hidden">
    </div>
    <div
      class="w-[350px] h-[350px] bg-pink-500/10 absolute -top-10 left-5 rounded-full z-0 blur-2xl sm:block hidden">
    </div>
  </div>
</div>
  </div>

<!--
<div class="container mx-auto sm:px-16 sm:px-16 px-4 lg:py-24 pb-16 pt-0">
  <div class="flex flex-wrap items-center justify-between">
    <div class="lg:w-1/2 w-full">
      <span class="block w-20 bg-slate-300 dark:bg-slate-700 h-px"></span>
      <h2 class="text-3xl font-extrabold text-slate-900 dark:text-slate-100 tracking-tight pt-10">The challenges that lie ahead</h2>
      <div class="max-w-lg mt-6 prose prose-primary dark:prose-invert">
        <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Aenean eu leo quam. Pellentesque ornare sem
          lacinia quam venenatis vestibulum. Donec ullamcorper nulla non metus auctor fringilla. Duis mollis, est non
          commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Integer posuere erat a ante
          venenatis dapibus posuere velit aliquet. Vestibulum id ligula porta felis euismod semper.</p>
        <p>Nullam id dolor id nibh ultricies vehicula ut id elit. Donec sed odio dui. Cras justo odio, dapibus ac
          facilisis in, egestas eget quam. Maecenas sed diam eget risus varius blandit sit amet non magna. Curabitur
          blandit tempus porttitor.</p>
        <%= link_to "#" do %>
          <span>View open roles</span>
          <%= icon "chevron-right", classes: "group-hover:transform group-hover:translate-x-1 group-hover:transition-transform group-hover:duration-300 ml-2 w-2 h-2 fill-current transform transition duration-300", variant: :solid %>
        <% end %>
      </div>
    </div>
    <div class="lg:w-1/2 w-full">
      <%= image_tag "challenges.png", alt: "Challenges", class: "max-w-full h-auto w-full" %>
    </div>
  </div>
</div>
-->

app/views/shared/_footer.html.erb
<footer class="container mx-auto px-4 pb-4">
  <nav role="Utility navigation">
    <ul class="lg:flex items-center justify-center text-center lg:my-6 mb-6 lg:text-base text-lg">
      <li class="py-3 lg:py-0">
        <%= link_to "Product", "#", class: "px-3 py-2 hover:text-primary-700 dark:hover:text-primary-500" %>
      </li>
      <li class="py-3 lg:py-0">
        <%= link_to "Customers", "#", class: "px-3 py-2 hover:text-primary-700 dark:hover:text-primary-500" %>
      </li>
      <li class="py-3 lg:py-0">
        <%= link_to "Features", "#", class: "px-3 py-2 hover:text-primary-700 dark:hover:text-primary-500" %>
      </li>
      <% if page_exists?("pricing") %>
        <li class="py-3 lg:py-0">
          <%= link_to "Pricing", pricing_path, class: "px-3 py-2 hover:text-primary-700 dark:hover:text-primary-500" %>
        </li>
      <% end %>
      <% if page_exists?("about") %>
        <li class="py-3 lg:py-0">
          <%= link_to "Company", about_path, class: "px-3 py-2 hover:text-primary-700  dark:hover:text-primary-500" %>
        </li>
      <% end %>
    </ul>
  </nav>

  <ul class="flex items-center justify-center space-x-6 mb-6">
    <li>
      <%= link_to "#", class: "group", target: :_blank do %>
        <%= icon "facebook", path: "social/facebook.svg", classes: "w-6 h-6 fill-current text-slate-400 group-hover:text-primary-600 dark:group-hover:text-primary-500" %>
      <% end %>
    </li>
    <li>
      <%= link_to "#", class: "group", target: :_blank do %>
        <%= icon "twitter", path: "social/twitter.svg", classes: "w-6 h-6 fill-current text-slate-400 group-hover:text-primary-600 dark:group-hover:text-primary-500" %>
      <% end %>
    </li>
    <li>
      <%= link_to "#", class: "group", target: :_blank do %>
        <%= icon "linkedin", path: "social/linkedin.svg", classes: "w-6 h-6 fill-current text-slate-400 group-hover:text-primary-600 dark:group-hover:text-primary-500" %>
      <% end %>
    </li>
    <li>
      <%= link_to "#", class: "group", target: :_blank do %>
        <%= icon "youtube", path: "social/youtube.svg", classes: "w-6 h-6 fill-current text-slate-400 group-hover:text-primary-600 dark:group-hover:text-primary-500" %>
      <% end %>
    </li>
  </ul>

  <p class="text-center text-slate-600 text-sm">&copy; <%= Railsui.config.application_name %> All Rights Reserved. <%= Railsui.config.theme.humanize %> theme by <a
      href="https://railsui.com" class="underline" target="_blank">Rails UI</a></p>
</footer>

app/views/shared/_nav_links.html.erb
<li>
  <%= nav_link_to "Home", send("root_path"), class:"nav-link"%>
</li>
<li>
  <%= nav_link_to "Articles", articles_path, class: "nav-link" %>
</li>
<li>
  <%= nav_link_to "About", send("about_path"), class: "nav-link" %>
</li>

app/views/shared/admin/_nav_links.html.erb
<li>
  <%= nav_link_to "Dashboard", send("admin_dashboard_path"), class: "nav-link" %>
</li>
<li>
  <%= nav_link_to "Projects", send("admin_projects_path"), class: "nav-link" %>
</li>
<li>
  <%= nav_link_to "Messages", send("admin_messages_path"), class: "nav-link" %>
</li>
<li>
  <%= nav_link_to "Assignments", send("admin_assignments_path"), class: "nav-link" %>
</li>
<li>
  <%= nav_link_to "Calendar", send("admin_calendar_path"), class: "nav-link" %>
</li>
<li>
  <%= nav_link_to "People", send("admin_people_path"), class: "nav-link" %>
</li>
<li>
  <%= nav_link_to "Activity", send("admin_activity_path"), class: "nav-link" %>
</li>
<li>
  <%= nav_link_to "Articles", articles_path, class: "nav-link" %>
</li>